### ISSUE TITLE
Change the warning message for words that have already been saved - Req 6-2

### ISSUE THREAD

**Issue by NaiaOzorio** [Pankwood/thewordsthatiknow#18]
Please review the message that is being displayed when a user tries to save a word that has been already saved to the database. Instead of a warning "Choose the words you know before save it" it should be "Word(s) has/have been already saved to the database. Please choose another word(s)."  

Reference: Requirement# 6 - item#2

GIVEN I am in the browser
WHEN I access the website
AND click on the "Check it" button
AND word(s) on green box(es) is/are displayed
AND I click on the "Save button"
THEN this/these word(s) should not be added again to the database
AND  a warning message advising that the word has already been saved previously should be displayed

![image](https://user-images.githubusercontent.com/108033786/197057630-8afc13df-df5d-4d3f-a099-596a4979d6a2.png)

**Comment by Pankwood** [comment]
I changed the text suggestion to "Word(s) has/have been already saved. Please choose another word(s).". 
I've removed this part of the sentence "to the database".

**Comment by Pankwood** [comment]
It has been published to stage and can be tested here:

https://thewordsthatiknow-app-git-stage-pankwood.vercel.app/
